### ISSUE TITLE
你好，请问一个模型，使用bertkeras中BERT处理文本，图像使用CNN，可以让着两个部分使用不同的学习率吗

### ISSUE THREAD

**Issue by zhangscofield** [Sniper970119/bert4keras_document#1]
我在做文本和图像融合的任务，使用BERT处理文本，CNN处理图像。但是BERT需要的学习率2e-5很小，导致CNN部分训练不出结果。写在一个模型中编译模型是优化器只用了一个学习率，有办法可以分开用两个学习率训练吗？我看苏神bert4keras的CRF的例子，有自定义层把学习率扩大1000倍的操作。要怎么自己写优化器实现？

**Comment by Sniper970119** [comment]
https://github.com/Sniper970119/bert4keras_document/tree/master/optimizers#def-extend_with_parameter_wise_lr_v2

**Comment by zhangscofield** [comment]
![image](https://user-images.githubusercontent.com/28681041/122673847-f9f1af00-d204-11eb-91d8-dde78a16d722.png)
像这样只限定bert4keras调用BERT部分的学习率为adam(2e-5)，而其他部分用adam默认学习率吗，extend_with_parameter_wise_lr_v2()不清楚怎么只限定BERT的部分

**Comment by zhangscofield** [comment]
自定义优化器似乎可以做到，但是对自义定优化器不知道该怎么写代码，所以想问一下能不能直接限定BERT的小学习率，模型其他部分为大学习率，因为看到example里都是只有optimizer=Adam(2e-5)，最后的CRF例子中自定义了层扩大1000倍。

**Comment by Sniper970119** [comment]
bert的参数名都是很规则的，名字限定一下不就行了。
至于你说的，没接触过苏神的相关使用

**Comment by zhangscofield** [comment]
![image](https://user-images.githubusercontent.com/28681041/122678495-bf464180-d219-11eb-94b9-57f49d8ccfe4.png)
请教一下，怎么用extend_with_parameter_wise_lr限定BERT部分整体的学习率

**Comment by Sniper970119** [comment]
你这个甚至都不是标准的python语句。

bert中每一层都有Transformer字样或者Embedding字样。可以通过这个过滤bert。

至于更多的，你需要自己探索，不提供保姆式服务

**Comment by zhangscofield** [comment]
感谢
